apiVersion: v1
kind: Pod
metadata:
        name: pod-pvc
spec:
        containers:
                - name: container-pod-pvc
                  image: nginx
                  volumeMounts:
                          - mountPath: /pod-pvc-path
                            name: vol-disk
        volumes:
                - name: vol-disk
                  persistentVolumeClaim:
                          claimName: disk1-pvc
