apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: disk1-pvc
spec:
        resources:
                requests:
                        storage: 1Gi
        accessModes:
                - ReadWriteOnce
        storageClassName: disk-st
