apiVersion: v1
kind: Pod
metadata:
     name: tom-pod-vol
spec:
     containers:
             - name: tom-vol-container
               image: tomcat
               volumeMounts:
                       - name: cache-volume
                         mountPath: /cache
     volumes:
             - name: cache-volume
               emptyDir: {}       
