apiVersion: v1
kind: Pod
metadata:
        name: tomcat-pod
        labels:
                app: tomcat
                tier: check
spec:
        containers:
                - name: tomcat-container
                  image: tomcat
