apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: tomcat-rs
spec:
        replicas: 3
        selector:
                matchExpressions:
                        - {key: app, operator: In, values: [tomcat-app]}
        template:
                metadata:
                        name: tomcat-pod
                        labels:
                                app: tomcat-app
                spec:
                        containers:
                                - name: tomcat-container
                                  image: tomcat
                                  ports:
                                          - containerPort: 8080
