apiVersion: v1
kind: PersistentVolume
metadata:
        name: pv-loc
spec:
        capacity:
                storage: 1Gi
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: loc-storage
        local:
                path: /home/disk1
        nodeAffinity:
                required:
                        nodeSelectorTerms:
                                - matchExpressions:
                                        - key: kubernetes.io/hostname
                                          operator: In
                                          values:
                                                  - k8.worker.three
