apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: pvc-loc
spec:
        resources:
                requests:
                        storage: 1Gi
        accessModes:
                - ReadWriteOnce
        storageClassName: loc-storage 
